# Generated by Django 5.1.4 on 2024-12-30 22:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(1, 'Start of working hours'), (2, 'End of working hours'), (3, 'Break start'), (4, 'Break end'), (5, 'Visit start'), (6, 'Visit end')])),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure_reason', models.IntegerField(choices=[(0, 'N/a'), (1, 'Legal'), (2, 'Illegal')], default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='agent.person')),
            ],
            options={
                'verbose_name': 'Attendance Event',
                'verbose_name_plural': 'Attendance Events',
            },
        ),
    ]
