# Generated by Django 5.1.2 on 2024-11-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceevent',
            options={'verbose_name': 'Attendance Event', 'verbose_name_plural': 'Attendance Events'},
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='reason',
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='arrival_reason',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('visit', 'Visit'), ('meeting', 'Meeting')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='departure_reason',
            field=models.CharField(blank=True, choices=[('end_of_shift', 'End of shift'), ('legal', 'Legal'), ('illegal', 'Illegal')], max_length=20, null=True),
        ),
    ]
