# Generated by Django 5.1.3 on 2024-11-08 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_attendanceevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
