# Generated by Django 5.1.3 on 2024-11-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_alter_attendanceevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceevent',
            name='arrival_reason',
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='event_type',
            field=models.CharField(choices=[('work_start', 'Start of working hours'), ('work_end', 'End of working hours'), ('break_start', 'Break start'), ('break_end', 'Break end'), ('visit_start', 'Visit start'), ('visit_end', 'Visit end')], max_length=20),
        ),
    ]
