# Generated by Django 5.1.3 on 2024-11-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_remove_attendanceevent_arrival_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='departure_reason',
            field=models.CharField(blank=True, choices=[('', '---------'), ('legal', 'Legal'), ('illegal', 'Illegal')], max_length=20, null=True),
        ),
    ]
