# Generated by Django 5.1.3 on 2024-11-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_alter_attendanceevent_departure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='departure_reason',
            field=models.IntegerField(blank=True, choices=[(0, '---------'), (1, 'Legal'), (2, 'Illegal')], null=True),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Start of working hours'), (2, 'End of working hours'), (3, 'Break start'), (4, 'Break end'), (5, 'Visit start'), (6, 'Visit end')]),
        ),
    ]
