# Generated by Django 5.1.4 on 2024-12-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('division_manager', 'Division Manager'), ('group_leader', 'Group Leader'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
