# Generated by Django 5.1.4 on 2024-12-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_customuser_managers_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Manager'), (2, 'Division Manager'), (3, 'Group Leader'), (4, 'Employee')], default=4),
        ),
    ]
