# Generated by Django 5.1.4 on 2024-12-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_person_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_divisions', to='agent.person'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='agent.person'),
        ),
        migrations.AddField(
            model_name='company',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_companies', to='agent.person', verbose_name='Leader'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
