# Generated by Django 5.1.3 on 2024-11-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_person_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='name_second',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
