# Generated by Django 5.1.4 on 2024-12-20 14:18

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_hierarchynode'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='divisions',
        ),
        migrations.AlterField(
            model_name='hierarchynode',
            name='parent_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Company'), (2, 'Division'), (3, 'Group')], null=True),
        ),
        migrations.CreateModel(
            name='UserHierarchyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Manager'), (2, 'Division Manager'), (3, 'Group Leader'), (4, 'Employee')], default=4)),
                ('hierarchy_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.hierarchynode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hierarchy_node')},
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='hierarchy_nodes',
            field=models.ManyToManyField(blank=True, related_name='users', through='agent.UserHierarchyNode', to='agent.hierarchynode'),
        ),
    ]
