# Generated by Django 5.1.3 on 2024-11-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_remove_person_name_person_name_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name_display',
            field=models.CharField(default='Alias', max_length=25),
        ),
        migrations.AddField(
            model_name='person',
            name='name_first',
            field=models.CharField(default='Nomen', max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_second',
            field=models.CharField(default='Omen', max_length=25),
        ),
    ]
