# Generated by Django 5.1.4 on 2024-12-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='position',
        ),
    ]
