# Generated by Django 5.1.4 on 2024-12-22 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_appuser_managers_remove_appuser_divisions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.AlterField(
            model_name='person',
            name='managed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='agent.userhierarchynode', verbose_name='Managed by'),
        ),
    ]
