# Generated by Django 5.1.3 on 2024-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_person_name_display_person_name_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='title_after',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('Ph.D.', 'Ph.D.'), ('MBA', 'MBA')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='title_before',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('Ph.D.', 'Ph.D.'), ('MBA', 'MBA')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.IntegerField(choices=[('employee', 'Employee'), ('guest', 'Guest'), ('contractor', 'Contractor'), ('supplier', 'Supplier'), ('customer', 'Customer'), ('other', 'Other')], default=1),
        ),
    ]
