# Generated by Django 5.1.4 on 2025-01-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_personcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='display_name',
            field=models.CharField(blank=True, default='Alias', max_length=25, null=True, verbose_name='Alias'),
        ),
    ]
