# Generated by Django 5.1.3 on 2024-12-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_person_title_after_person_title_before_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name_display',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name_first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name_second',
            new_name='second_name',
        ),
    ]
