# Generated by Django 5.1.4 on 2025-01-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_person_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('role_in_team', models.CharField(blank=True, help_text='Role osoby v týmu', max_length=50, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='agent.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='agent.team')),
            ],
            options={
                'verbose_name': 'Přiřazení zaměstnance do týmu',
                'verbose_name_plural': 'Přiřazení zaměstnanců do týmů',
                'unique_together': {('person', 'team')},
            },
        ),
    ]
