# Generated by Django 5.1.4 on 2025-01-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_personteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='personteam',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of members'),
        ),
        migrations.AddField(
            model_name='team',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of members'),
        ),
    ]
