# Generated by Django 5.1.3 on 2024-12-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_rename_name_display_person_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='second_name',
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Omen', max_length=25, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='display_name',
            field=models.CharField(default='Alias', max_length=25, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='Nomen', max_length=25, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.CharField(max_length=100, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Guest'), (3, 'Contractor'), (4, 'Supplier'), (5, 'Customer'), (6, 'Other')], default=6, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_after',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('Ph.D.', 'Ph.D.'), ('MBA', 'MBA')], max_length=10, verbose_name='Title After'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_before',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('Ph.D.', 'Ph.D.'), ('MBA', 'MBA')], max_length=10, verbose_name='Title Before'),
        ),
    ]
