# Generated by Django 5.1.4 on 2025-01-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_personteam_count_team_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personteam',
            name='count',
        ),
    ]
