# Generated by Django 5.1.3 on 2024-12-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_remove_person_second_name_person_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title_after',
            field=models.CharField(blank=True, choices=[('DiS.', 'DiS.'), ('MBA', 'MBA'), ('LL.M.', 'LL.M.'), ('CSc.', 'CSc.'), ('DrSc.', 'DrSc.'), ('Ph.D.', 'Ph.D.')], max_length=10, verbose_name='Title After'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_before',
            field=models.CharField(blank=True, choices=[('Bc.', 'Bc.'), ('BcA.', 'BcA.'), ('RNDr.', 'RNDr.'), ('MUDr.', 'MUDr.'), ('JUDr.', 'JUDr.'), ('PhDr.', 'PhDr.'), ('Ing.', 'Ing.'), ('Mgr..', 'Mgr.')], max_length=10, verbose_name='Title Before'),
        ),
    ]
