# Generated by Django 5.1.4 on 2025-01-03 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_remove_personteam_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcompany',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_companies', to='agent.person', verbose_name='Person reference'),
        ),
    ]
