# Generated by Django 5.1.4 on 2025-01-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_alter_personcompany_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcompany',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_persons', to='agent.company', verbose_name='Company reference'),
        ),
    ]
