# Generated by Django 5.1.3 on 2024-12-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_division_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='divisions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
