# Generated by Django 5.1.4 on 2025-01-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_alter_personcompany_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personteam',
            options={'verbose_name': 'Employee Assignment to Team', 'verbose_name_plural': 'Employee Assignments to Teams'},
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams_for_person', through='agent.PersonTeam', to='agent.person'),
        ),
        migrations.AlterField(
            model_name='personteam',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_teams', to='agent.person'),
        ),
        migrations.AlterField(
            model_name='personteam',
            name='role_in_team',
            field=models.CharField(blank=True, help_text='Role of the person in the team', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='agent.team'),
        ),
    ]
