# Generated by Django 5.1.4 on 2025-01-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_alter_personteam_options_team_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
