# Generated by Django 5.1.4 on 2025-01-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_remove_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personteam',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_teams', to='agent.person'),
        ),
    ]
