Table WorkDay {
  id Integer [primary key]
  employee_id Integer [ref: > Person.id, not null]
  date Date [not null]
  total_work_hours Decimal(5, 2) [not null]
  total_legal_break Decimal(5, 2) [default: 0, not null]
  total_illegal_break Decimal(5, 2) [default: 0, not null]

  indexes {
    (employee_id, date) [unique]
  }
  Note: "Work Day"
}

Table WorkDayAssignment {
  id Integer [primary key]
  workday_id Integer [ref: > WorkDay.id, not null]
  project_id Integer [ref: > Project.id, not null]
  assigned_hours Decimal(5, 2) [not null]
  work_performed Varchar(100) [not null]

  indexes {
    (workday_id, project_id) [unique]
  }

  Note: "Work Day Assignment"
}
Table Person {
  id Integer [primary key]
  unique_id Varchar(20) [unique, not null]
  name_display Varchar(25) [default: "Alias", not null]
  name_first Varchar(25) [default: "Nomen", not null]
  name_second Varchar(25) [default: "Omen", not null]
  organization Varchar(100) [not null]
  role Varchar(10) [not null]

  Note: "Person"
}

Table Project {
  id Integer [primary key]
  code Integer [unique, not null]
  name Varchar(70) [not null]
  description Text
  Note: "Project"
}

Table AttendanceEvent {
  id integer [primary key]
  person_id integer [ref: > Person.id, not null]
  event_type integer [not null]
  event_time timestamp [default: 'timezone.now', not null]
  timestamp timestamp [default: 'timezone.now', not null]
  departure_reason integer [default: 0, not null] Note: "Attendance Event"
}
