Table WorkDay {
  id Integer [primary key]
  employee_id Integer [ref: > Person.id, not null]
  date Date [not null]
  total_work_hours Decimal(5, 2) [not null]
  total_legal_break Decimal(5, 2) [default: 0, not null]
  total_illegal_break Decimal(5, 2) [default: 0, not null]
  indexes {
    (employee_id, date) [unique]
  }

  Note: "Work Day"
}

Table Person {
  id Integer [primary key]
  unique_id Varchar(20) [unique, not null]
  name_display Varchar(25) [default: "Alias", not null]
  name_first Varchar(25) [default: "Nomen", not null]
  name_second Varchar(25) [default: "Omen", not null]
  organization Varchar(100) [not null]
  role Varchar(10) [not null]

  Note: "Person"
}