# Generated by Django 5.1.4 on 2024-12-30 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code of the project, e.g., 25R001, 25K001.', max_length=9, unique=True, verbose_name='Project Code')),
                ('name', models.CharField(max_length=70, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the project.', verbose_name='Description')),
                ('start_date', models.DateField(blank=True, help_text='Date when the project starts.', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Date when the project is expected to end.', null=True, verbose_name='End Date')),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, help_text='Planned number of hours for the project.', max_digits=10, verbose_name='Planned Hours')),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0, help_text='Worked number of hours on the project.', max_digits=10, verbose_name='Worked Hours')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Completed'), (3, 'Canceled')], default=0, help_text='Project status: 0 = new, 1 = in progress, 2 = completed, 3 = canceled.', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='PersonProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(verbose_name='Assigned At')),
                ('role_in_project', models.CharField(max_length=50, verbose_name='Role in Project')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.person', verbose_name='Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Person-Project Assignment',
                'verbose_name_plural': 'Person-Project Assignments',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Work Date')),
                ('hours_allocated', models.DecimalField(decimal_places=2, help_text='Number of hours allocated to the project on the given date.', max_digits=5, verbose_name='Hours Allocated')),
                ('description', models.TextField(blank=True, help_text='Description of the work done.', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.person', verbose_name='Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Work Log',
                'verbose_name_plural': 'Work Logs',
            },
        ),
    ]
