# Generated by Django 5.1.3 on 2024-12-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(help_text='Code of the project, e.g., 25R001, 25K001.', max_length=14, unique=True, verbose_name='Project Code'),
        ),
    ]
