# Generated by Django 5.1.3 on 2024-12-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Planned number of hours for the project.', max_digits=10, verbose_name='Planned Hours'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Completed'), (3, 'Canceled')], default=0, help_text='Project status: 0 = new, 1 = in progress, 2 = completed, 3 = canceled.', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='worked_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Worked number of hours on the project.', max_digits=10, verbose_name='Worked Hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(help_text='Code of the project, e.g., 25R001, 25K001.', max_length=9, unique=True, verbose_name='Project Code'),
        ),
    ]
