# Generated by Django 5.1.3 on 2024-12-10 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_person_title_after_person_title_before_and_more'),
        ('order', '0004_project_planned_hours_project_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('role_in_project', models.CharField(max_length=50, verbose_name='Role in Project')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.person', verbose_name='Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Person-Project Assignment',
                'verbose_name_plural': 'Person-Project Assignments',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Work Date')),
                ('hours_allocated', models.DecimalField(decimal_places=2, help_text='Number of hours allocated to the project on the given date.', max_digits=5, verbose_name='Hours Allocated')),
                ('description', models.TextField(blank=True, help_text='Description of the work done.', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.person', verbose_name='Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Work Log',
                'verbose_name_plural': 'Work Logs',
            },
        ),
    ]
